<?php

namespace MusicXML\Map;

/**
 * Maps MusicXML element tags to their corresponding PHP model classes.
 *
 * This class contains a central mapping used by the parser to instantiate
 * the correct model object for each XML element encountered.
 *
 * @author Kamshory
 */
class ModelMap
{
    /**
     * The main class map.
     * Keys are the MusicXML element tag names (e.g., 'score-partwise'),
     * and values are the fully qualified class names of the corresponding model classes.
     */
    const CLASS_MAP = array(
        'accent' => \MusicXML\Model\Accent::class,
        'accidental' => \MusicXML\Model\Accidental::class,
        'accidental-mark' => \MusicXML\Model\AccidentalMark::class,
        'accidental-text' => \MusicXML\Model\AccidentalText::class,
        'accord' => \MusicXML\Model\Accord::class,
        'accordion-high' => \MusicXML\Model\AccordionHigh::class,
        'accordion-middle' => \MusicXML\Model\AccordionMiddle::class,
        'accordion-registration' => \MusicXML\Model\AccordionRegistration::class,
        'actual-notes' => \MusicXML\Model\ActualNotes::class,
        'appearance' => \MusicXML\Model\Appearance::class,
        'arpeggiate' => \MusicXML\Model\Arpeggiate::class,
        'arrow' => \MusicXML\Model\Arrow::class,
        'arrow-direction' => \MusicXML\Model\ArrowDirection::class,
        'arrowhead' => \MusicXML\Model\Arrowhead::class,
        'articulations' => \MusicXML\Model\Articulations::class,
        'assess' => \MusicXML\Model\Assess::class,
        'attributes' => \MusicXML\Model\Attributes::class,
        'backup' => \MusicXML\Model\Backup::class,
        'bar-style' => \MusicXML\Model\BarStyle::class,
        'double' => \MusicXML\Model\XDouble::class,
        'function' => \MusicXML\Model\XFunction::class,
        'principal-voice' => \MusicXML\Model\PrincipalVoice::class,
        'pull-off' => \MusicXML\Model\PullOff::class,
        'pppp' => \MusicXML\Model\Pppp::class,
        'ppppp' => \MusicXML\Model\Ppppp::class,
        'pppppp' => \MusicXML\Model\Pppppp::class,
        'prefix' => \MusicXML\Model\Prefix::class,
        'pre-bend' => \MusicXML\Model\PreBend::class,
        'release' => \MusicXML\Model\Release::class,
        'rest' => \MusicXML\Model\Rest::class,
        'rf' => \MusicXML\Model\Rf::class,
        'rfz' => \MusicXML\Model\Rfz::class,
        'right-divider' => \MusicXML\Model\RightDivider::class,
        'right-margin' => \MusicXML\Model\RightMargin::class,
        'root' => \MusicXML\Model\Root::class,
        'root-alter' => \MusicXML\Model\RootAlter::class,
        'root-step' => \MusicXML\Model\RootStep::class,
        'scaling' => \MusicXML\Model\Scaling::class,
        'schleifer' => \MusicXML\Model\Schleifer::class,
        'scoop' => \MusicXML\Model\Scoop::class,
        'score-instrument' => \MusicXML\Model\ScoreInstrument::class,
        'score-part' => \MusicXML\Model\ScorePart::class,
        'score-partwise' => \MusicXML\Model\ScorePartwise::class,
        'score-timewise' => \MusicXML\Model\ScoreTimewise::class,
        'second' => \MusicXML\Model\Second::class,
        'semi-pitched' => \MusicXML\Model\SemiPitched::class,
        'senza-misura' => \MusicXML\Model\SenzaMisura::class,
        'sf' => \MusicXML\Model\Sf::class,
        'sffz' => \MusicXML\Model\Sffz::class,
        'sfp' => \MusicXML\Model\Sfp::class,
        'sfpp' => \MusicXML\Model\Sfpp::class,
        'sfz' => \MusicXML\Model\Sfz::class,
        'shake' => \MusicXML\Model\Shake::class,
        'sign' => \MusicXML\Model\Sign::class,
        'string' => \MusicXML\Model\XString::class,
        'touching-pitch' => \MusicXML\Model\TouchingPitch::class,
        'transpose' => \MusicXML\Model\Transpose::class,
        'tremolo' => \MusicXML\Model\Tremolo::class,
        'trill-mark' => \MusicXML\Model\TrillMark::class,
        'triple-tongue' => \MusicXML\Model\TripleTongue::class,
        'tuplet' => \MusicXML\Model\Tuplet::class,
        'tuplet-type' => \MusicXML\Model\TupletType::class,
        'tuning-alter' => \MusicXML\Model\TuningAlter::class,
        'tuning-octave' => \MusicXML\Model\TuningOctave::class,
        'turn' => \MusicXML\Model\Turn::class,
        'type' => \MusicXML\Model\Type::class,
        'unstress' => \MusicXML\Model\Unstress::class,
        'up-bow' => \MusicXML\Model\UpBow::class,
        'virtual-instrument' => \MusicXML\Model\VirtualInstrument::class,
        'virtual-library' => \MusicXML\Model\VirtualLibrary::class,
        'virtual-name' => \MusicXML\Model\VirtualName::class,
        'voice' => \MusicXML\Model\Voice::class,
        'volume' => \MusicXML\Model\Volume::class,
        'wait' => \MusicXML\Model\Wait::class,
        'wavy-line' => \MusicXML\Model\WavyLine::class,
        'wedge' => \MusicXML\Model\Wedge::class,
        'wood' => \MusicXML\Model\Wood::class,
        'words' => \MusicXML\Model\Words::class,
        'word-font' => \MusicXML\Model\WordFont::class,
        'work' => \MusicXML\Model\Work::class,
        'work-number' => \MusicXML\Model\WorkNumber::class,
        'work-title' => \MusicXML\Model\WorkTitle::class,
        'part-list' => \MusicXML\Model\PartList::class,
        'part-name' => \MusicXML\Model\PartName::class,
        'part-abbreviation' => \MusicXML\Model\PartAbbreviation::class,
        'midi-instrument' => \MusicXML\Model\MidiInstrument::class,
        'midi-channel' => \MusicXML\Model\MidiChannel::class,
        'midi-program' => \MusicXML\Model\MidiProgram::class,
        'part' => \MusicXML\Model\PartPartwise::class,
        'measure' => \MusicXML\Model\Measure::class,
        'measure-partwise' => \MusicXML\Model\MeasurePartwise::class,
        'divisions' => \MusicXML\Model\Divisions::class,
        'key' => \MusicXML\Model\Key::class,
        'fifths' => \MusicXML\Model\Fifths::class,
        'mode' => \MusicXML\Model\Mode::class,
        'time' => \MusicXML\Model\Time::class,
        'beats' => \MusicXML\Model\Beats::class,
        'beat-type' => \MusicXML\Model\BeatType::class,
        'clef' => \MusicXML\Model\Clef::class,
        'line' => \MusicXML\Model\Line::class,
        'note' => \MusicXML\Model\Note::class,
        'pitch' => \MusicXML\Model\Pitch::class,
        'step' => \MusicXML\Model\Step::class,
        'octave' => \MusicXML\Model\Octave::class,
        'duration' => \MusicXML\Model\Duration::class,
        'stem' => \MusicXML\Model\Stem::class,
        'chord' => \MusicXML\Model\Chord::class,
        'identification' => \MusicXML\Model\Identification::class,
        'rights' => \MusicXML\Model\Rights::class,
        'encoding' => \MusicXML\Model\Encoding::class,
        'software' => \MusicXML\Model\Software::class,
        'encoding-date' => \MusicXML\Model\EncodingDate::class,
        'supports' => \MusicXML\Model\Supports::class,
        'alter' => \MusicXML\Model\Alter::class,
        'lyric' => \MusicXML\Model\Lyric::class,
        'syllabic' => \MusicXML\Model\Syllabic::class,
        'text' => \MusicXML\Model\TextElement::class,
        'notations' => \MusicXML\Model\Notations::class,
        'tied' => \MusicXML\Model\Tied::class,
        'tie' => \MusicXML\Model\Tie::class,
        'unpitched' => \MusicXML\Model\Unpitched::class,
        'display-step' => \MusicXML\Model\DisplayStep::class,
        'display-octave' => \MusicXML\Model\DisplayOctave::class,
        'instrument' => \MusicXML\Model\Instrument::class,
        'notehead' => \MusicXML\Model\Notehead::class,
        'midi-device' => \MusicXML\Model\MidiDevice::class,
        'midi-unpitched' => \MusicXML\Model\MidiUnpitched::class,
        'pan' => \MusicXML\Model\Pan::class,
        'instrument-sound' => \MusicXML\Model\InstrumentSound::class,
        'staves' => \MusicXML\Model\Staves::class,
        'direction' => \MusicXML\Model\Direction::class,
        'direction-type' => \MusicXML\Model\DirectionType::class,
        'metronome' => \MusicXML\Model\Metronome::class,
        'beat-unit' => \MusicXML\Model\BeatUnit::class,
        'per-minute' => \MusicXML\Model\PerMinute::class,
        'sound' => \MusicXML\Model\Sound::class,
        'dot' => \MusicXML\Model\Dot::class,
        'forward' => \MusicXML\Model\Forward::class,
        'artificial' => \MusicXML\Model\Artificial::class
    );
}